### ISSUE TITLE
Use "review requested" GitHub feature instead of "needs-review" label

### ISSUE THREAD

**Issue by danuker** [chevah/github-hooks-server#18]
When requesting a review via the GitHub interface (from "Reviewers") from any person, the hook should take it as a "needs-review" command.

This will help us use the [review-requested report](https://github.com/pulls/review-requested), while keeping labels and assignees in sync.

**Comment by adiroiban** [comment]
So.... when a review is requested... the 'needs-review' label should be automatically removed ...and 'need-schanges' or 'needs-merge' should be removed.

The assigne can continue to be the PR owner/driver.

Then a change is reqested via the GitHub PR option, the need-changes label should be applied

If a change is approved, if there are no more reviewers left, it should add 'needs-merge'
otherwise, do nothing.

**Comment by danuker** [comment]
We ran into this [here](https://github.com/chevah/sftpplus.com/pull/594).

```12/20/2021, 2:17:36.435 PM	[pull_request_review][None] New review from adi as approved All good. Thanks! [...]```

This log entry means `_setApproveChanges` was triggered. But there were no `remaining_reviewers`, because `current_reviewers` was already `ioanacristinamarinescu`. There was never a `needs-review` instruction/label either.

We should probably subscribe to "review requested" events and treat them as "needs-review" commands.

----

> So.... when a review is requested... the 'needs-review' label should be automatically removed

I suspect you mean "should be automatically added".

**Comment by adiroiban** [comment]
Also somehow releated... If "Review requested" GitHub action is not used, but instead a "needs-review" comment is left the hook server should automatically (re)request the review for the needed reviewers ... without using the "assignees" field.

To help with https://github.com/pulls/review-requested report :)
